### ISSUE TITLE
code and initial dataset

### ISSUE THREAD

**Issue by DryPilgrim** [shizhl/Confucius#1]
请问作者
1. code and initial dataset什么时候开源呢？
2. 论文中说“Parameter Correctness measures the correctness of the input parameter type for the tools, which validates whether the LLM response conforms to the schema of the tool’s interface.”  能具体说一下Parameter Correctness的计算公式吗？

非常感谢您的回答：）

**Comment by shizhl** [comment]
Thank you for your attention!
1. You can see the ##Dataset section in the readme now.
2. For each parameter, the model generates the parameter type, e.g., int and str, and the parameter content, e.g., 123. We compare token-level similarity between the generated parameter and ground truth for evaluation.

Please send me an email for further discussion.
