### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by air-tea** [shizhl/Confucius#2]
Thanks for your excellent work! 
I have some trouble accessing your dataset from google drive, do you plan to make another copy in baidu cloud or other platforms?
By the way, do you plan to opensource the code for the evaluation?

**Comment by lucenzhong** [comment]
@shizhl Hello, I have the same issue. Failed to access your dataset from google drive.

**Comment by shizhl** [comment]
Thank you for your attention. I've changed the permissions. Could you please try again?
